export const PLUS = 'PLUS'
export const MINUS = 'MINUS'
export const FETCH_DATA = 'FETCH_DATA'
export const POST = 'POST'
export const DELETE = 'DELETE'
export const EDIT_POST = 'EDIT_POST' // edit in the apps window
export const SHOW_LOADER = 'SHOW_LOADER'
export const HIDE_LOADER = 'HIDE_LOADER'
export const SHOW_ALERT = 'SHOW_ALERT'